#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ENV_DIR = resolve(ROOT, 'environments');
const SCHEMA_FILE = resolve(ENV_DIR, 'local.env.example');

function parseArgs(argv) {
    const opts = {
        env: process.env.BUILD_ENV || 'local',
        force: false,
        strict: false,
        quiet: false,
    };
    for (const arg of argv) {
        if (arg.startsWith('--env=')) opts.env = arg.slice('--env='.length);
        else if (arg.startsWith('--build=')) opts.env = arg.slice('--build='.length);
        else if (arg === '--force' || arg === '-f') opts.force = true;
        else if (arg === '--strict') opts.strict = true;
        else if (arg === '--quiet' || arg === '-q') opts.quiet = true;
        else if (!arg.startsWith('-')) opts.env = arg;
    }
    return opts;
}

function parseSchemaKeys(contents) {
    const keys = [];
    for (const line of contents.split(/\r?\n/)) {
        const match = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=/.exec(line);
        if (match) keys.push(match[1]);
    }
    return keys;
}

function encodeValue(value) {
    const escaped = String(value)
        .replace(/\\/g, '\\\\')
        .replace(/"/g, '\\"')
        .replace(/\r?\n/g, '\\n');
    return `"${escaped}"`;
}

export function main(argv = process.argv.slice(2)) {
    const opts = parseArgs(argv);

    if (!/^[A-Za-z0-9_-]+$/.test(opts.env)) {
        console.error(`error: invalid env name: ${opts.env}`);
        return 1;
    }

    if (!existsSync(SCHEMA_FILE)) {
        console.error(`error: schema file not found: ${SCHEMA_FILE}`);
        return 1;
    }

    const keys = parseSchemaKeys(readFileSync(SCHEMA_FILE, 'utf8'));
    if (keys.length === 0) {
        console.error(`error: no keys found in schema file: ${SCHEMA_FILE}`);
        return 1;
    }

    const target = resolve(ENV_DIR, `${opts.env}.env`);
    const isCI = Boolean(process.env.CI) && process.env.CI !== 'false';

    if (existsSync(target) && !opts.force && !isCI) {
        console.error(
            `error: ${target} already exists. Refusing to overwrite ` +
                `(pass --force to regenerate).`,
        );
        return 1;
    }

    const missing = [];
    const lines = [
        '# Generated by scripts/generate-env.mjs - do not commit.',
        `# Environment: ${opts.env}`,
        '',
    ];
    for (const key of keys) {
        const raw = process.env[key];
        if (raw === undefined || raw === '') missing.push(key);
        lines.push(`${key}=${encodeValue(raw === undefined ? '' : raw)}`);
    }
    lines.push('');

    mkdirSync(ENV_DIR, { recursive: true });
    writeFileSync(target, lines.join('\n'), 'utf8');

    const provided = keys.length - missing.length;
    if (!opts.quiet) {
        console.log(
            `Generated environments/${opts.env}.env ` +
                `(${provided}/${keys.length} keys provided via environment).`,
        );
        if (missing.length > 0) {
            console.warn(
                `warning: ${missing.length} key(s) unset and written empty: ` +
                    missing.join(', '),
            );
        }
    }

    if (opts.strict && missing.length > 0) {
        console.error(`error: --strict set and ${missing.length} key(s) missing.`);
        return 1;
    }

    return 0;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    process.exitCode = main();
}
